### ISSUE TITLE
What should the package structure of the apis be?

### ISSUE THREAD

**Issue by i509VCB** [QuiltMC/quilt-standard-libraries#10]
One discussion that has come up on discord has been how should we organize the package structure of the modules.

So far I've seen a some ideas for the package structure.
- `org.quiltmc.qsl.event.api` (qsl.\<module>.api)
- `org.quiltmc.qsl.api.event` (qsl.api.\<module>)

The purpose of this issue is to discuss which package structure should be used. If there are any other package structures, do comment your idea.

**Comment by i509VCB** [comment]
My opinion here as a comment separate from the main issue entry:

I'd lean towards the earlier option, `org.quiltmc.qsl.api.event`.
My reason is that it makes package discovery much easier vs going through the very wide `qsl` package and then having to slap `.api` on the end.

**Comment by Haven-King** [comment]
`org.quiltmc.qsl.module.api` makes the most sense to me, as it keeps the API and impl classes together and makes it more clear that these modules are distinct from one another. With `org.quiltmc.qsl.api.module`, module API classes are more related to each other than they are their own implementation. For instance:
`org.quiltmc.qsl.api.event`
`org.quiltmc.qsl.api.networking`
Are more closely related than, say
`org.quiltmc.qsl.api.event`
`org.quiltmc.qsl.impl.event`
Which is just not an accurate representation of the package structure.

**Comment by LambdAurora** [comment]
The issue with a `org.quiltmc.qsl.module.api` structure is it hurts more the modders as it reduces discoverability, it just makes stuff harder to find because if you have an auto-completion, it can auto-completes `org.quiltmc.qsl.api.module`, while the other one is already harder. Same when browsing javadocs, go into the API package and you have a list of every modules with their description.

**Comment by Leo40Git** [comment]
I also lean towards `org.quiltmc.qsl.$module.api`.

**Comment by CheaterCodes** [comment]
I just want to throw another option into the ring:

We could have `org.quiltmc.qsl.<module>` for the api and `org.quiltmc.qsl.<module>.internal` for the implementation stuff.
I personally like this because the api packages have simple names with good discovery and the internal packages are still local to the structure.

I've heard the argument that it's ugly to have `internal` in the middle of the other packages, but I fail to see this as an issue.

An api that uses this format is e.g. the gradle api.

**Comment by egelja** [comment]
I too would prefer `org.quiltmc.qsl.<module>` and `org.quiltmc.qsl.<module>.internal`, since you get the advantage of higher discoverability while still keeping the API/implementation packages related.

The internal package could even be named `_internal` to make it clearer that it shouldn't be used.

**Comment by LambdAurora** [comment]
Definitely not a fan of the internal package being a subpackage of what's supposed to be API.

**Comment by TheGlitch76** [comment]
I agree that `.internal` is less clear than `org.quiltmc.qsl.module.api/impl`. However, both of these are still clearer solutions than `org.quiltmc.qsl.api/impl.module`

**Comment by TheGlitch76** [comment]
We have voted on the issue and have decided on using `org.quiltmc.qsl.$module.api` and `org.quiltmc.qsl.$module.impl`.

Thank you to everyone who participated in the discussion!
