### ISSUE TITLE
Fire behaves wrongly

### ISSUE THREAD

**Issue by hallamuck** [QuiltMC/quilt-standard-libraries#240]
Fire can only be lit on the top faces of solid blocks, as opposed to being able to be lit on any face of a flammable block. Any pre-existing fire that isn't on the top face of a solid block will extinguish quickly.

Versions:
mc 1.19.3
ql 17.8, 18.1-beta.25
qfapi 5.0.0-alpha.5, 5.0.0-alpha.6
qsl 4.0.0-beta.2
fapi 0.68.1, 0.69.1

**Comment by EnnuiL** [comment]
~~Oh, I almost forgot to mention: This was actually a QSL issue! And it was caused by 1.19.3 changes breaking how the capturing of vanilla flammables worked; This has been fixed since QSL 4.0.0-beta.3, which QFAPI 5.0.0-alpha.6 includes~~

past ennui had failed me ;-;
5.0.0-alpha.6 still had QSL 4.0.0-beta.2, meaning that the issue wasn't fixed there; oh well, next update will have QSL 4.0.0-beta.3

**Comment by EnnuiL** [comment]
Quilted Fabric API 5.0.0-alpha.7 has updated to QSL 4.0.0-beta.3 now (and for real this time :P)
This will fix the issue
