### ISSUE TITLE
"Middle" resource pack inject event

### ISSUE THREAD

**Issue by exaskye** [QuiltMC/quilt-standard-libraries#243]
Right now, there are two events for injecting resource packs — "Default", which injects "as vanilla", so to speak, and "Top", which injects after everything else — even user packs, making it a hard override. (Also, it seems that it's injected too late for it to change biomes, somehow? But I believe this is a bug.)

It would be nice if there was another API that injected "as mods", i.e. somewhere in the middle. Say, at the end of ResourceLoaderImpl.appendModResourcePacks? [:)](https://git.sleeping.town/unascribed/QDResLoader/src/branch/trunk/src/main/java/com/unascribed/qdresloader/mixin/MixinResourceLoaderImpl.java)

As it stands, Default is no good if you need to override things defined in other mods, and Top is no good if you want to respect user packs or add biomes/etc.

**Comment by LambdAurora** [comment]
Looking at the mod which would use it, I'm not entirely sure this event is actually the right approach.

It feels like using the `ResourceLoader#registerResourcePackProfileProvider` would be more appropriate for the mod as it means those resource packs are actually visible to the end-user and not hidden away inside the Default resource pack (or worse hidden entirely through the "Top" event).

It also means it's actual separate packs. Though I can see an issue with them not always being default enabled, which can be fixed in resource loader.

> (Also, it seems that it's injected too late for it to change biomes, somehow? But I believe this is a bug.)

Proves how finicky this API is to get right and to maintain. "Top" resource packs are really annoying to implement, but they are useful.

**Comment by exaskye** [comment]
> Though I can see an issue with them not always being default enabled, which can be fixed in resource loader.

Yes, this is why I didn't use that API. The whole point of this mod is it's loaded by default.

I don't have strong feelings about how this is accomplished, the event just looked from the outside like the most appropriate way to expose it given the current API surface. Default-on profiles would be fine.

**Comment by lukebemish** [comment]
You should already be able to make default enabled profiles with `ResourceLoader#registerResourcePackProfileProvider`. I do it in DynAssetGen, but I forget what the trick or weirdness was.

**Comment by Leo40Git** [comment]
...don't you just use `ResourcePackActivationType.DEFAULT_ENABLED`?

**Comment by exaskye** [comment]
Currently, the activation type is only available when registering "built-in packs", which have to be at predetermined locations inside your mod jar. The linked PR adds this functionality to resource pack profiles, and is the proposed solution.

**Comment by LambdAurora** [comment]
You can't really do that with any pack, atm that value isn't stored in the pack profiles, nor is it queried from profiles that don't have the Quilt built-in resource pack source.

This is changed in the latest PR.
