### ISSUE TITLE
QSL 4.0.0-beta.12 and above incompatible with Enhanced Block Entities

### ISSUE THREAD

**Issue by FoundationGames** [QuiltMC/quilt-standard-libraries#279]
The GroupResourcePack flattening change introduced a redirect which replaces EBE's inject target for adding its own resources directly after vanilla
[EBE - LifecycledResourceManagerImplMixin](https://github.com/FoundationGames/EnhancedBlockEntities/blob/014168895fa7137d9bef73a4dc7045d98437ae5d/src/main/java/foundationgames/enhancedblockentities/mixin/LifecycledResourceManagerImplMixin.java#L27)
[QSL - MultiPackResourceManagerMixin](https://github.com/QuiltMC/quilt-standard-libraries/blob/744ccf5d8e5692055590617dabdadb6e82a8dc98/library/core/resource_loader/src/main/java/org/quiltmc/qsl/resource/loader/mixin/MultiPackResourceManagerMixin.java#L66)

This results in EBE's resource packs never being applied when using QSL versions 4.0.0 beta 12 and above, as shown in [EnhancedBlockEntities#136](https://github.com/FoundationGames/EnhancedBlockEntities/issues/136)

**Comment by LambdAurora** [comment]
Fix is incoming as I found out that `@ModifyVariable` modifies locals which I did not understand prior to a discussion.
Which allows me to make the QSL injection much much better.

Though, in the process of debugging I found out an issue in EBE itself, `INVOKE_ASSIGN` makes it so the injected pack is not present in the `packs` field of the class, using `INVOKE` instead should fix it. This is very important because QSL may recompute namespaces and it could lead to the pack being voided.
